### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Khitiara** [robotbrain/ForgeTheSane#1]
- [x] Fetch libraries and mc client jar
- [x] Get binpatch and forge from installer
- [x] Postprocess
- [ ] Get some sort of diff between postprocessed and original
